# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odins < Formula
  desc "The All-Father of Local DNS — Local DNS + Reverse Proxy manager for macOS"
  homepage "https://github.com/adialaleal/odins"
  version "0.9.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/adialaleal/odins/releases/download/v0.9.1/odins_0.9.1_darwin_amd64.tar.gz"
    sha256 "9f00ef3a54c406fa5b27ff78de3d9f42f569dbfc7b1fd2bc26d539e3a85eba07"

    define_method(:install) do
      bin.install "odins"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/adialaleal/odins/releases/download/v0.9.1/odins_0.9.1_darwin_arm64.tar.gz"
    sha256 "ed9c3faf76a6c244050c0a63b100d7bd5cdfe20f52c4b17b687469b13edeea20"

    define_method(:install) do
      bin.install "odins"
    end
  end

  test do
    assert_match "ODINS", shell_output("#{bin}/odins --help")
  end
end
