# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odins < Formula
  desc "The All-Father of Local DNS — Local DNS + Reverse Proxy manager for macOS"
  homepage "https://github.com/adialaleal/odins"
  version "0.6.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/adialaleal/odins/releases/download/v0.6.0/odins_0.6.0_darwin_amd64.tar.gz"
    sha256 "b4ef3a1a02b9861da2a955cd55a2711f5e3ff86eb7e820313284b975f4fec1f8"

    define_method(:install) do
      bin.install "odins"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/adialaleal/odins/releases/download/v0.6.0/odins_0.6.0_darwin_arm64.tar.gz"
    sha256 "5ee0bedfa723af68a208f0ffb42a4834dad9e6aeb8d43a31b292571421c391fd"

    define_method(:install) do
      bin.install "odins"
    end
  end

  test do
    assert_match "ODINS", shell_output("#{bin}/odins --help")
  end
end
